package common_enumerations;

public enum Medal 
{
	SIGNUP(10),
	FIRSTADOPT(25),
	FIRSTABANDON(0),
	FIRSTBATTLEWON(100),
	FIRSTBATTLELOST(10),
	WONTWENTY(30),
	WONFIFTY(60),
	WONHUNDRED(110),
	UNDEFEATEDHUNDRED(65000),
	FIRSTFORUMPOST(5),
	FIRSTEVOLUTION(25),
	STAFF(40),
	MODERATOR(40),
	ADMIN(40),
	PLAYEDFORYEAR(500),
	PLAYEDFORTWOYEARS(750),
	PLAYEDFORTHREEPLUS(1500),
	LIKEDONFACEBOOK(5),
	LIKEDONTWITTER(5),
	FIRSTBAN(-300),
	SECONDBAN(-10000),
	LASTBAN(-1000000);
	
	private int value;
	
	private Medal(int value)
	{
		this.value = value;
	}
	
	public int getValue()
	{
		return this.value;
	}
}
